language: en-US
markdown: redcarpet
redcarpet:
  extensions: [
    autolink,
    disable_indented_code_blocks,
    fenced_code_blocks,
    footnotes,
    no_intra_emphasis,
    space_after_headers,
    strikethrough,
    tables,
    underline
  ]
tagline: Will it blend?
title: Tracy & Pasha
url: http://www.katsutley.us
